GROUP_REPOS = [
  {
    "name": "WeKnow",
    "gitLinks": ["https://github.com/DevOps-Valgfag/WhoKnows"],
    "backend": "https://we-know.dk",
    "frontend": "https://we-know.dk",
    "monitoring": "",
    "stack": ["Ruby", "Sinatra", "sqLite3", "bcrypt", "puma", "Docker compose","nginx"],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "MixedLaptops",
    "gitLinks": ["https://github.com/MixedLaptops/oggole"],
    "backend": "http://20.254.43.177:8080/",
    "frontend": "http://20.254.43.177:8080/",
    "monitoring": "",
    "stack": ["GO", "SQlite"],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "5%_uptime_gang",
    "gitLinks": ["https://github.com/5-uptime-gang/whoknows_variations"],
    "backend": "http://68.221.201.252:8080/",
    "frontend": "http://68.221.201.252:8080/",
    "monitoring": "",
    "stack": ["GO", "gin"],
    "documentation": [],
    "sla": "",
},
{
    "name": "DVK-DevOps",
    "gitLinks": ["https://github.com/DVK-DEVOPS/DVK-Project"],
    "backend": "https://whoknows-dvk.dk/",
    "frontend": "https://whoknows-dvk.dk/",
    "monitoring": "",
    "stack": ["Go", "Gorilla", "SQLite", "Swaggo", "nginx", "Docker Compose"],
    "documentation": [],
    "sla": "",
},
  {
    "name": "Martin-s-angels",
    "gitLinks": ["https://github.com/Martin-s-angels/whoknows_variations_devops"],
    "backend": "http://68.221.202.43:8080/",
    "frontend": "http://68.221.202.43:8080/",
    "monitoring": "",
    "stack": ["Ruby", "Sinatra"],
    "documentation": [],
    "sla": "",
},
  {
    "name": "devkopa",
    "gitLinks": ["https://github.com/devkopa/WhoKnows-legacy", "https://github.com/devkopa/WhoKnows-next-gen"],
    "backend": "http://51.107.217.98:3000/",
    "frontend": "http://51.107.217.98:3000/",
    "monitoring": "",
    "stack": ["Ruby", "Rails", "React", "PostgreSQL", "bcrypt", "puma"],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "CodeLab-DevOps",
    "gitLinks": ["https://github.com/CodeLab-DevOps/whoknows_elixir_monolith", "https://github.com/CodeLab-DevOps/Starter-WhoKnows-"],
    "backend": "http://209.38.235.238:4000",
    "frontend": "http://209.38.235.238:4000/",
    "monitoring": "",
    "stack": [],
    "documentation": ["Elixir", "Phoneix", "Sqlite"],
    "sla": "",
  },
  {
    "name": "GitDenGas123456",
    "gitLinks": ["https://github.com/GitDenGas123456/DevOps-Valgfag"],
    "backend": "http://4.235.104.246:8080/",
    "frontend": "http://4.235.104.246:8080/",
    "monitoring": "",
    "stack": ["Go", "Gorilla"],
    "documentation": [],
    "sla": "",  
  },
]
