GROUP_REPOS = [
  {
    "name": "devkopa",
    "gitLinks": ["https://github.com/devkopa/pythondevops"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "Devops-valgfag",
    "gitLinks": ["https://github.com/DevOps-Valgfag/WhoKnows"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "MixedLaptops",
    "gitLinks": ["https://github.com/MixedLaptops/oggole"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "5%_uptime_gang",
    "gitLinks": ["https://github.com/5-uptime-gang/whoknows_variations"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
  {
    "name": "Martin-s-angels",
    "gitLinks": ["https://github.com/Martin-s-angels/whoknows_variations_devops"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
]
