GROUP_REPOS = [
  {
    "name": "WeKnow",
    "gitLinks": ["https://github.com/DevOps-Valgfag/WhoKnows"],
    "backend": "http://51.107.222.64:8080/",
    "frontend": "http://51.107.222.64:8080/",
    "monitoring": "",
    "stack": ["Ruby", "Sinatra", "sqLite3", "bcrypt", "puma"],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "MixedLaptops",
    "gitLinks": ["https://github.com/MixedLaptops/oggole"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "5%_uptime_gang",
    "gitLinks": ["https://github.com/5-uptime-gang/whoknows_variations"],
    "backend": "http://68.221.201.252:8080/",
    "frontend": "http://68.221.201.252:8080/",
    "monitoring": "",
    "stack": ["GO", "gin"],
    "documentation": [],
    "sla": "",
},
{
    "name": "DVK-DevOps",
    "gitLinks": ["https://github.com/DVK-DEVOPS/DVK-Project"],
    "backend": "http://51.142.201.55:8080/",
    "frontend": "http://51.142.201.55:8080/",
    "monitoring": "",
    "stack": ["Go", "Gorilla"],
    "documentation": [],
    "sla": "",
},
  {
    "name": "Martin-s-angels",
    "gitLinks": ["https://github.com/Martin-s-angels/whoknows_variations_devops"],
    "backend": "http://68.221.202.43:8080/",
    "frontend": "http://68.221.202.43:8080/",
    "monitoring": "",
    "stack": ["Ruby", "Sinatra"],
    "documentation": [],
    "sla": "",
},
  {
    "name": "devkopa",
    "gitLinks": ["https://github.com/devkopa/WhoKnows-legacy", "https://github.com/devkopa/WhoKnows-next-gen"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
  },
  {
    "name": "CodeLab-DevOps",
    "gitLinks": ["https://github.com/CodeLab-DevOps/whoknows_elixir_monolith", "https://github.com/CodeLab-DevOps/Starter-WhoKnows-"],
    "backend": "http://209.38.235.238:4000",
    "frontend": "http://209.38.235.238:4000/",
    "monitoring": "",
    "stack": [],
    "documentation": ["Elixir", "Phoneix", "Sqlite"],
    "sla": "",
  },
  "name": "GitDenGas123456",
    "gitLinks": ["https://github.com/GitDenGas123456/DevOps-Valgfag"],
    "backend": "",
    "frontend": "https://whoknows-rewrite-g0axgwcaacc8g4d7.swedencentral-01.azurewebsites.net/",
    "monitoring": "",
    "stack": ["Go", "Gorilla"],
    "documentation": [],
    "sla": "",
]
